name = "scrimble-consumer"
main = "worker-consumer.ts"
compatibility_date = "2024-03-08"

[[d1_databases]]
binding = "DB"
database_name = "scrimble"
database_id = "d3b8a50c-89ff-47a8-9aaa-58802343bd73"

[vars]
ENVIRONMENT = "production"
FIREBASE_PROJECT_ID = "scrimble-auth"

[[queues.consumers]]
queue = "scrimble"
max_batch_size = 1
max_batch_timeout = 30
