#:schema node_modules/wrangler/config-schema.json
name = "scrimble"
pages_build_output_dir = "dist"
compatibility_date = "2024-03-08"

[[d1_databases]]
binding = "DB"
database_name = "scrimble"
database_id = "d3b8a50c-89ff-47a8-9aaa-58802343bd73"

[[r2_buckets]]
binding = "CHECKPOINT_BUCKET"
bucket_name = "scrimble"

[vars]
ENVIRONMENT = "production"
FIREBASE_PROJECT_ID = "scrimble-auth"
PROJECT_GENERATION_RUNTIME = "durable_object"

[[queues.producers]]
binding = "AGENT_QUEUE"
queue = "scrimble"

[[durable_objects.bindings]]
name = "PROJECT_GENERATOR"
class_name = "ProjectGeneratorDO"
script_name = "scrimble-consumer"
