name = "scrimble-consumer"
main = "worker-consumer.ts"
compatibility_date = "2024-03-08"

[[d1_databases]]
binding = "DB"
database_name = "scrimble"
database_id = "d3b8a50c-89ff-47a8-9aaa-58802343bd73"

[[r2_buckets]]
binding = "CHECKPOINT_BUCKET"
bucket_name = "scrimble"

[vars]
ENVIRONMENT = "production"
FIREBASE_PROJECT_ID = "scrimble-auth"

[[queues.producers]]
binding = "AGENT_QUEUE"
queue = "scrimble"

[[queues.consumers]]
queue = "scrimble"
max_batch_size = 1
max_batch_timeout = 60

[observability]
enabled = true

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
