import chalk from 'chalk';
import { stdin as input, stdout as output } from 'node:process';
import { createInterface } from 'node:readline/promises';
import type { DiscoveryMode, DiscoveryStep, Intent } from '@scrimble/shared';
import {
  approveFoundation,
  buildAutogeneratedFoundation,
  buildCustomFoundation,
  buildInteractiveFoundation,
  loadDiscoveryBootstrap,
  persistDiscoveryDraft,
  persistDiscoveryProgress,
  skipFoundation,
  type FoundationAnswers,
} from './foundation.js';

const DISCOVERY_QUALITY_OPTIONS = ['prototype', 'production', 'enterprise'] as const;
const DISCOVERY_TIMELINE_OPTIONS = ['asap', 'flexible', 'long_term'] as const;

const INTERACTIVE_QUESTIONS: Array<{
  field: keyof FoundationAnswers;
  prompt: string;
}> = [
  { field: 'projectName', prompt: 'Project name' },
  { field: 'goal', prompt: 'Core goal / product objective' },
  { field: 'productVision', prompt: 'Product vision statement' },
  { field: 'targetUsers', prompt: 'Target users' },
  { field: 'successCriteria', prompt: 'Success criteria (semicolon-separated)' },
  { field: 'nonGoals', prompt: 'Non-goals / out-of-scope (semicolon-separated)' },
  { field: 'qualityPreference', prompt: 'Quality bar (prototype|production|enterprise)' },
  { field: 'timeline', prompt: 'Timeline preference (asap|flexible|long_term)' },
  { field: 'productConstraints', prompt: 'Product constraints (semicolon-separated)' },
  { field: 'technicalConstraints', prompt: 'Technical constraints (semicolon-separated)' },
  { field: 'designDirection', prompt: 'Design / UX direction (optional)' },
];

function parseListValue(inputValue: string): string[] {
  return [...new Set(
    inputValue
      .split(/\r?\n|;/)
      .map((entry) => entry.trim())
      .filter((entry) => entry.length > 0),
  )];
}

function listToPromptDefault(value: string[] | undefined): string {
  if (!value || value.length === 0) {
    return '';
  }
  return value.join('; ');
}

function draftToAnswers(intent: Intent | undefined): Partial<FoundationAnswers> {
  if (!intent) {
    return {};
  }
  return {
    projectName: intent.projectName,
    goal: intent.goal,
    productVision: intent.productVision,
    targetUsers: intent.targetUsers,
    successCriteria: intent.successCriteria,
    nonGoals: intent.nonGoals,
    qualityPreference: intent.qualityPreference,
    timeline: intent.timeline,
    productConstraints: intent.productConstraints,
    technicalConstraints: intent.technicalConstraints,
    ...(intent.designDirection ? { designDirection: intent.designDirection } : {}),
  };
}

function toFoundationAnswers(
  answers: Partial<FoundationAnswers>,
  draft: Intent | undefined,
  repoName: string,
): FoundationAnswers {
  return {
    projectName: String(answers.projectName ?? draft?.projectName ?? repoName),
    goal: String(answers.goal ?? draft?.goal ?? 'Define project goal'),
    productVision: String(answers.productVision ?? answers.goal ?? draft?.productVision ?? 'Define product vision'),
    targetUsers: String(answers.targetUsers ?? draft?.targetUsers ?? 'Primary users'),
    successCriteria: answers.successCriteria ?? draft?.successCriteria ?? ['Core workflow works end-to-end'],
    nonGoals: answers.nonGoals ?? draft?.nonGoals ?? ['Do not rewrite unrelated modules'],
    qualityPreference: answers.qualityPreference ?? draft?.qualityPreference ?? 'production',
    timeline: answers.timeline ?? draft?.timeline ?? 'flexible',
    productConstraints: answers.productConstraints ?? draft?.productConstraints ?? [],
    technicalConstraints: answers.technicalConstraints ?? draft?.technicalConstraints ?? [],
    ...(answers.designDirection ? { designDirection: answers.designDirection } : {}),
  };
}

function normalizeInteractiveField(
  answers: Partial<FoundationAnswers>,
  field: keyof FoundationAnswers,
  rawValue: string,
): Partial<FoundationAnswers> {
  const trimmed = rawValue.trim();
  if (field === 'successCriteria' || field === 'nonGoals' || field === 'productConstraints' || field === 'technicalConstraints') {
    return { ...answers, [field]: parseListValue(trimmed) };
  }
  if (field === 'qualityPreference') {
    const normalized = trimmed.toLowerCase();
    const selected = DISCOVERY_QUALITY_OPTIONS.find((entry) => entry === normalized) ?? 'production';
    return { ...answers, qualityPreference: selected };
  }
  if (field === 'timeline') {
    const normalized = trimmed.toLowerCase();
    const selected = DISCOVERY_TIMELINE_OPTIONS.find((entry) => entry === normalized) ?? 'flexible';
    return { ...answers, timeline: selected };
  }
  return { ...answers, [field]: trimmed };
}

async function promptWithDefault(
  rl: ReturnType<typeof createInterface>,
  label: string,
  defaultValue?: string,
): Promise<string> {
  const question = defaultValue && defaultValue.length > 0
    ? `${label} [${defaultValue}]: `
    : `${label}: `;
  const answer = (await rl.question(question)).trim();
  if (!answer && defaultValue) {
    return defaultValue;
  }
  return answer;
}

function printScanSummary(log: (message?: string) => void, scan: {
  projectType: string;
  repoName: string;
  repoPath: string;
  branch?: string | undefined;
  languages: string[];
  frameworks: string[];
  packageManager?: string | undefined;
  hasConductorArtifacts: boolean;
}): void {
  log('');
  log(chalk.bold('Project discovery required before execution.'));
  log(chalk.dim(`  Repo: ${scan.repoName} (${scan.repoPath})`));
  log(chalk.dim(`  Type: ${scan.projectType}`));
  log(chalk.dim(`  Branch: ${scan.branch ?? '-'}`));
  log(chalk.dim(`  Languages: ${scan.languages.join(', ') || 'unknown'}`));
  log(chalk.dim(`  Frameworks: ${scan.frameworks.join(', ') || 'none detected'}`));
  log(chalk.dim(`  Package manager: ${scan.packageManager ?? 'unknown'}`));
  if (scan.hasConductorArtifacts) {
    log(chalk.dim('  Conductor context detected and will be imported as hints.'));
  }
  log('');
}

function printDraftSummary(log: (message?: string) => void, draft: Intent): void {
  log(chalk.bold('Discovery draft'));
  log(chalk.dim(`  Project: ${draft.projectName}`));
  log(chalk.dim(`  Goal: ${draft.goal}`));
  log(chalk.dim(`  Users: ${draft.targetUsers}`));
  log(chalk.dim(`  Quality: ${draft.qualityPreference}`));
  log(chalk.dim(`  Timeline: ${draft.timeline}`));
  if (draft.successCriteria.length > 0) {
    log(chalk.dim(`  Success criteria: ${draft.successCriteria.join(' | ')}`));
  }
  if (draft.nonGoals.length > 0) {
    log(chalk.dim(`  Non-goals: ${draft.nonGoals.join(' | ')}`));
  }
  log('');
}

function parseMode(inputValue: string): DiscoveryMode | 'skip' | undefined {
  const normalized = inputValue.trim().toLowerCase();
  if (normalized === 'skip' || normalized === 's') {
    return 'skip';
  }
  if (normalized.startsWith('i')) {
    return 'interactive';
  }
  if (normalized.startsWith('a')) {
    return 'autogenerate';
  }
  if (normalized.startsWith('c')) {
    return 'custom';
  }
  return undefined;
}

export interface EnsureDiscoveryFoundationOptions {
  cwd: string;
  prompt: string;
  interactive: boolean;
  autoApprove: boolean;
  log: (message?: string) => void;
}

export async function ensureDiscoveryFoundation(options: EnsureDiscoveryFoundationOptions): Promise<boolean> {
  const bootstrap = await loadDiscoveryBootstrap(options.cwd);
  if (!bootstrap.requiresDiscovery) {
    return true;
  }

  const scan = bootstrap.scan;
  printScanSummary(options.log, scan);

  if (!options.interactive) {
    if (!options.autoApprove) {
      options.log(chalk.red('Cannot continue in non-interactive mode without an approved foundation.'));
      options.log(chalk.dim('Run `scrimble --prompt "<request>" --yes` to auto-approve discovery, or run `scrimble` interactively.'));
      options.log('');
      return false;
    }
    const draft = await buildAutogeneratedFoundation(
      options.cwd,
      scan,
      options.prompt,
      bootstrap.state.draft ?? bootstrap.currentIntent,
    );
    await persistDiscoveryDraft(options.cwd, draft, 'autogenerate', scan);
    await approveFoundation(options.cwd, draft, 'autogenerate', scan);
    options.log(chalk.green(`Approved project foundation for ${draft.projectName} from one-shot request.`));
    options.log('');
    return true;
  }

  const rl = createInterface({ input, output });
  try {
    let mode: DiscoveryMode | undefined = bootstrap.state.mode;
    let step: DiscoveryStep = bootstrap.state.step ?? 'mode_selection';
    let questionIndex = bootstrap.state.questionIndex ?? 0;
    let draft = bootstrap.state.draft;
    let answers: Partial<FoundationAnswers> = draftToAnswers(draft);

    for (;;) {
      if (!mode || step === 'scan_summary' || step === 'mode_selection') {
        const defaultMode: DiscoveryMode = mode ?? 'autogenerate';
        const modeAnswer = await promptWithDefault(
          rl,
          'Discovery mode (interactive|autogenerate|custom|skip)',
          defaultMode,
        );
        const parsed = parseMode(modeAnswer);
        if (!parsed) {
          options.log(chalk.yellow('Invalid mode. Use interactive, autogenerate, custom, or skip.'));
          continue;
        }
        if (parsed === 'skip') {
          await skipFoundation(options.cwd);
          options.log(chalk.yellow('Project foundation skipped by user choice.'));
          options.log('');
          return true;
        }

        mode = parsed;
        step = mode === 'interactive'
          ? 'interactive_questions'
          : mode === 'custom'
            ? 'custom_brief'
            : 'autogenerate_goal';
        questionIndex = 0;
        await persistDiscoveryProgress(
          options.cwd,
          mode,
          step,
          scan,
          draft,
          step === 'interactive_questions' ? questionIndex : undefined,
        );
      }

      if (step === 'autogenerate_goal') {
        const goal = await promptWithDefault(rl, 'Core goal', draft?.goal ?? options.prompt);
        draft = await buildAutogeneratedFoundation(options.cwd, scan, goal, draft ?? bootstrap.currentIntent);
        mode = 'autogenerate';
        step = 'draft_review';
        await persistDiscoveryDraft(options.cwd, draft, mode, scan);
        printDraftSummary(options.log, draft);
        continue;
      }

      if (step === 'custom_brief') {
        const brief = await promptWithDefault(
          rl,
          'Custom project brief',
          draft?.productVision ?? options.prompt,
        );
        draft = await buildCustomFoundation(options.cwd, scan, brief, draft ?? bootstrap.currentIntent);
        mode = 'custom';
        step = 'draft_review';
        await persistDiscoveryDraft(options.cwd, draft, mode, scan);
        printDraftSummary(options.log, draft);
        continue;
      }

      if (step === 'interactive_questions') {
        if (!mode) {
          mode = 'interactive';
        }
        if (!draft) {
          const initialGoal = bootstrap.currentIntent?.goal ?? options.prompt;
          draft = await buildAutogeneratedFoundation(options.cwd, scan, initialGoal, bootstrap.currentIntent);
          answers = draftToAnswers(draft);
        }
        while (questionIndex < INTERACTIVE_QUESTIONS.length) {
          const question = INTERACTIVE_QUESTIONS[questionIndex];
          if (!question) {
            break;
          }
          const defaultValue = question.field === 'successCriteria'
            ? listToPromptDefault(answers.successCriteria)
            : question.field === 'nonGoals'
              ? listToPromptDefault(answers.nonGoals)
              : question.field === 'productConstraints'
                ? listToPromptDefault(answers.productConstraints)
                : question.field === 'technicalConstraints'
                  ? listToPromptDefault(answers.technicalConstraints)
                  : String(answers[question.field] ?? '');
          const answerValue = await promptWithDefault(rl, question.prompt, defaultValue);
          answers = normalizeInteractiveField(answers, question.field, answerValue);
          questionIndex += 1;
          await persistDiscoveryProgress(options.cwd, mode, step, scan, draft, questionIndex);
        }

        const finalized = toFoundationAnswers(answers, draft, scan.repoName);
        draft = await buildInteractiveFoundation(options.cwd, scan, finalized, draft ?? bootstrap.currentIntent);
        mode = 'interactive';
        step = 'draft_review';
        questionIndex = 0;
        await persistDiscoveryDraft(options.cwd, draft, mode, scan);
        printDraftSummary(options.log, draft);
        continue;
      }

      if (step === 'draft_review' && draft) {
        const action = (await promptWithDefault(
          rl,
          'Review action (approve|edit|regenerate|skip)',
          'approve',
        )).toLowerCase();

        if (action === 'approve' || action === 'a') {
          await approveFoundation(options.cwd, draft, mode ?? 'autogenerate', scan);
          options.log(chalk.green(`Approved project foundation for ${draft.projectName}.`));
          options.log('');
          return true;
        }
        if (action === 'skip' || action === 's') {
          await skipFoundation(options.cwd);
          options.log(chalk.yellow('Project foundation skipped by user choice.'));
          options.log('');
          return true;
        }
        if (action === 'edit' || action === 'e') {
          mode = 'interactive';
          step = 'interactive_questions';
          questionIndex = 0;
          answers = draftToAnswers(draft);
          await persistDiscoveryProgress(options.cwd, mode, step, scan, draft, questionIndex);
          continue;
        }
        if (action === 'regenerate' || action === 'r') {
          mode = 'autogenerate';
          step = 'autogenerate_goal';
          await persistDiscoveryProgress(options.cwd, mode, step, scan, draft);
          continue;
        }

        options.log(chalk.yellow('Invalid action. Use approve, edit, regenerate, or skip.'));
        continue;
      }

      step = 'mode_selection';
      if (!mode) {
        mode = 'autogenerate';
      }
      await persistDiscoveryProgress(options.cwd, mode, step, scan, draft);
    }
  } finally {
    rl.close();
  }
}
