import * as fs from 'node:fs/promises';
import * as os from 'node:os';
import * as path from 'node:path';
import {
  CONFIG_FILE,
  PROVIDER_VALIDATION_CACHE_FILE,
  SCRIMBLE_DIR,
  type Intent,
  type ProfileValidationCacheEntry,
} from '@scrimble/shared';
import { ConversationalOrchestrator } from '../agent/orchestrator.js';
import type {
  OperatorBoundary,
  OperatorBoundaryResolution,
  OperatorEvent,
  OperatorRunOptions,
  OperatorRunResult,
} from '../agent/types.js';
import {
  approveFoundation,
  buildAutogeneratedFoundation,
  buildCustomFoundation,
  buildInteractiveFoundation,
  loadDiscoveryBootstrap,
  persistDiscoveryDraft,
} from '../discovery/foundation.js';
import { ensureDiscoveryFoundation } from '../discovery/plaintext.js';
import { mutateLedger, readLedger } from '../ledger/storage.js';
import {
  buildDefaultScrimbleConfig,
  buildProviderProfile,
  getActiveProfile,
  upsertProfile,
} from '../ai/profiles.js';
import { getDefaultApiKeyPlaceholder, refreshProfileHealth } from '../ai/provider.js';
import { writeSecureJson } from '../security.js';
import { loadScrimbleConfig } from '../config/load-config.js';
import { CANONICAL_VALIDATION_SCENARIOS, materializeScenarioFixture } from './fixtures.js';
import {
  evaluateScenarioFailures,
  rankFailures,
  summarizeFoundation,
  summarizeLedgerSnapshot,
  summarizeTaskQuality,
} from './taxonomy.js';
import type {
  ValidationBoundaryDecision,
  ValidationFlowKind,
  ValidationOutcomeSummary,
  ValidationRecoveryEvent,
  ValidationRunReport,
  ValidationScenarioDefinition,
  ValidationScenarioReport,
  ValidationTimelineEvent,
  ValidationProviderSummary,
} from './types.js';

export interface ValidationHarnessOptions {
  keepFixtures?: boolean;
}

interface FlowExecutionArtifacts {
  ledger: Awaited<ReturnType<typeof readLedger>>;
  outcomes: ValidationOutcomeSummary[];
  timeline: ValidationTimelineEvent[];
  boundaryDecisions: ValidationBoundaryDecision[];
  recoveryEvents: ValidationRecoveryEvent[];
}

function mapOperatorEvent(event: OperatorEvent): ValidationTimelineEvent {
  return {
    type: event.type,
    ...(event.action ? { action: event.action } : {}),
    message: event.message,
    ...(event.reason ? { reason: event.reason } : {}),
  };
}

function mapOutcome(result: OperatorRunResult): ValidationOutcomeSummary {
  return {
    status: result.status,
    summary: result.summary,
    ...(result.reason ? { reason: result.reason } : {}),
    ...(result.nextSuggestedAction ? { nextSuggestedAction: result.nextSuggestedAction } : {}),
    ...(result.recoveryKind ? { recoveryKind: result.recoveryKind } : {}),
    recoveryActions: (result.recoveryActions ?? []).map((action) => action.kind),
    ...(result.lastFailure ? { lastFailure: result.lastFailure } : {}),
  };
}

function captureRecoveryEvents(
  source: ValidationFlowKind,
  result: OperatorRunResult,
): ValidationRecoveryEvent[] {
  const events: ValidationRecoveryEvent[] = [];
  if (result.recoveryKind) {
    events.push({
      kind: result.recoveryKind,
      summary: result.summary,
      source,
    });
  }
  for (const action of result.recoveryActions ?? []) {
    events.push({
      kind: action.kind,
      summary: action.description,
      source,
    });
  }
  return events;
}

function staleValidationTimestamp(): string {
  return new Date(Date.now() - (2 * 24 * 60 * 60 * 1000)).toISOString();
}

function applyScenarioEnvOverrides(
  overrides: Record<string, string | undefined> | undefined,
): () => void {
  const mergedOverrides: Record<string, string | undefined> = {
    OPENAI_API_KEY: process.env['OPENAI_API_KEY'] ?? 'validation-openai-key',
    ...(overrides ?? {}),
  };
  const previousValues = new Map<string, string | undefined>();
  for (const [key, value] of Object.entries(mergedOverrides)) {
    previousValues.set(key, process.env[key]);
    if (value === undefined) {
      delete process.env[key];
    } else {
      process.env[key] = value;
    }
  }
  return () => {
    for (const [key, previous] of previousValues.entries()) {
      if (previous === undefined) {
        delete process.env[key];
      } else {
        process.env[key] = previous;
      }
    }
  };
}

async function applyProviderSetup(
  cwd: string,
  scenario: ValidationScenarioDefinition,
): Promise<void> {
  if (!scenario.providerSetup) {
    return;
  }

  const setup = scenario.providerSetup;
  const profileProvider = setup.provider ?? 'openai';
  let config = buildDefaultScrimbleConfig('guide', profileProvider);

  if (setup.clearProfiles) {
    config = {
      ...config,
      profiles: [],
      activeProfileId: undefined,
    };
  } else {
    const active = getActiveProfile(config);
    const profile = buildProviderProfile({
      id: active?.id,
      name: active?.name ?? `${profileProvider} validation profile`,
      provider: profileProvider,
      modelStrategy: setup.modelStrategy
        ?? (profileProvider === 'github-copilot' ? 'auto' : 'explicit'),
      model: setup.model,
      authStrategy: setup.authStrategy
        ?? (profileProvider === 'github-copilot' ? 'env_token' : 'api_key'),
      apiKey: profileProvider === 'github-copilot' ? undefined : getDefaultApiKeyPlaceholder(profileProvider),
      token: profileProvider === 'github-copilot' ? undefined : undefined,
      interactive: false,
    });
    config = upsertProfile(config, profile, true);
  }

  await fs.mkdir(path.join(cwd, SCRIMBLE_DIR), { recursive: true });
  await writeSecureJson(path.join(cwd, SCRIMBLE_DIR, CONFIG_FILE), config);

  if (setup.seedStaleCapabilities) {
    const active = getActiveProfile(config);
    if (active) {
      const staleTime = staleValidationTimestamp();
      const staleEntry: ProfileValidationCacheEntry = {
        profileId: active.id,
        provider: active.provider,
        authStrategy: active.auth.strategy,
        authStatus: 'ready',
        authSource: active.provider === 'github-copilot' ? 'env:COPILOT_GITHUB_TOKEN' : 'env:OPENAI_API_KEY',
        modelStrategy: active.modelStrategy,
        ...(active.model ? { model: active.model } : {}),
        modelAvailability: 'available',
        capability: {
          source: 'cached',
          availableModels: ['stale-model'],
          validatedAt: staleTime,
          stale: true,
        },
        issues: [],
        usabilityIssues: [],
        validatedAt: staleTime,
      };
      await fs.writeFile(
        path.join(cwd, SCRIMBLE_DIR, PROVIDER_VALIDATION_CACHE_FILE),
        `${JSON.stringify({
          version: 1,
          updatedAt: staleTime,
          profiles: {
            [active.id]: staleEntry,
          },
        }, null, 2)}\n`,
        'utf8',
      );
    }
  }
}

async function summarizeProviderState(cwd: string): Promise<ValidationProviderSummary> {
  try {
    const config = await loadScrimbleConfig(cwd);
    const active = getActiveProfile(config);
    if (!active) {
      return {
        hasActiveProfile: false,
        usableNow: false,
      };
    }
    const health = await refreshProfileHealth(active, { cwd });
    return {
      hasActiveProfile: true,
      profileName: active.name,
      provider: active.provider,
      usableNow: health.usableNow,
      authStatus: health.status,
      ...(health.authSource ? { authSource: health.authSource } : {}),
      capabilitySource: health.capabilitySource,
      validationFreshness: health.validationFreshness,
      modelAvailability: health.modelAvailability,
    };
  } catch {
    return {
      hasActiveProfile: false,
      usableNow: false,
    };
  }
}

function makeBoundaryResolver(
  source: ValidationFlowKind,
  options: {
    pauseAtFirstExecutionBoundary: boolean;
    decisions: ValidationBoundaryDecision[];
    recoveryEvents: ValidationRecoveryEvent[];
  },
): (boundary: OperatorBoundary) => Promise<OperatorBoundaryResolution> {
  let executionPauseUsed = false;
  return async (boundary) => {
    const pauseEligibleActions = new Set([
      'configure_ai',
      'generate_or_update_tasks',
      'recover_failed_tasks',
      'execute_tasks',
      'repair_state',
    ]);
    const shouldPause =
      options.pauseAtFirstExecutionBoundary &&
      !executionPauseUsed &&
      pauseEligibleActions.has(boundary.action);
    const resolution: OperatorBoundaryResolution = shouldPause ? { kind: 'pause' } : { kind: 'proceed' };
    options.decisions.push({
      action: boundary.action,
      reason: boundary.reason,
      decision: resolution.kind,
    });
    if (shouldPause) {
      executionPauseUsed = true;
      options.recoveryEvents.push({
        kind: 'pending_approval',
        summary: `Paused on boundary: ${boundary.reason}`,
        source,
      });
    }
    return resolution;
  };
}

async function runRecoveryFollowUp(
  orchestrator: ConversationalOrchestrator,
  source: ValidationFlowKind,
  runOptions: OperatorRunOptions,
  outcomes: ValidationOutcomeSummary[],
  recoveryEvents: ValidationRecoveryEvent[],
): Promise<void> {
  const latestOutcome = outcomes[outcomes.length - 1];
  if (!latestOutcome || (latestOutcome.status !== 'blocked' && latestOutcome.status !== 'failed')) {
    return;
  }

  const followUp = await orchestrator.runRequest('recover failed tasks and continue execution', {
    ...runOptions,
    autoConfirm: true,
  });
  outcomes.push(mapOutcome(followUp));
  recoveryEvents.push(...captureRecoveryEvents(source, followUp));
}

async function resolveShellDiscovery(
  cwd: string,
  scenario: ValidationScenarioDefinition,
): Promise<Intent | null> {
  const bootstrap = await loadDiscoveryBootstrap(cwd);
  if (!bootstrap.requiresDiscovery) {
    return bootstrap.currentIntent;
  }

  const previousIntent = bootstrap.state.draft ?? bootstrap.currentIntent;
  const mode = scenario.discovery.shellMode;
  let draft: Intent;

  if (mode === 'autogenerate') {
    draft = await buildAutogeneratedFoundation(cwd, bootstrap.scan, scenario.prompt, previousIntent);
  } else if (mode === 'custom') {
    const brief = scenario.discovery.customBrief ?? scenario.prompt;
    draft = await buildCustomFoundation(cwd, bootstrap.scan, brief, previousIntent);
  } else {
    const baseline = await buildAutogeneratedFoundation(cwd, bootstrap.scan, scenario.prompt, previousIntent);
    const answers = scenario.discovery.interactiveAnswers ?? {
      projectName: baseline.projectName,
      goal: baseline.goal,
      productVision: baseline.productVision,
      targetUsers: baseline.targetUsers,
      successCriteria: baseline.successCriteria,
      nonGoals: baseline.nonGoals,
      qualityPreference: baseline.qualityPreference,
      timeline: baseline.timeline,
      productConstraints: baseline.productConstraints,
      technicalConstraints: baseline.technicalConstraints,
      ...(baseline.designDirection ? { designDirection: baseline.designDirection } : {}),
    };
    draft = await buildInteractiveFoundation(cwd, bootstrap.scan, answers, baseline);
  }

  await persistDiscoveryDraft(cwd, draft, mode, bootstrap.scan);
  await approveFoundation(cwd, draft, mode, bootstrap.scan);
  return draft;
}

async function injectConsistencyMismatch(cwd: string): Promise<void> {
  await mutateLedger(cwd, (ledger) => {
    const now = new Date().toISOString();
    ledger.runtime.activeExecution = {
      taskId: 'missing-task-for-validation',
      workerId: 'gemini',
      startedAt: now,
      attempt: 1,
      phase: 'executing',
      statusMessage: 'Injected mismatch for recovery validation.',
    };
    ledger.runtime.updatedAt = now;
    ledger.updatedAt = now;
  });
}

async function runShellAdjacentFlow(
  cwd: string,
  scenario: ValidationScenarioDefinition,
): Promise<FlowExecutionArtifacts> {
  const timeline: ValidationTimelineEvent[] = [];
  const boundaryDecisions: ValidationBoundaryDecision[] = [];
  const recoveryEvents: ValidationRecoveryEvent[] = [];
  const outcomes: ValidationOutcomeSummary[] = [];
  const restoreEnv = applyScenarioEnvOverrides(scenario.envOverrides);
  try {
    await applyProviderSetup(cwd, scenario);
    await resolveShellDiscovery(cwd, scenario);
    timeline.push({
      type: 'discovery',
      message: `Shell-adjacent discovery resolved with mode ${scenario.discovery.shellMode}.`,
    });

    const orchestrator = new ConversationalOrchestrator(cwd);
    const runOptions: OperatorRunOptions = {
      interactionMode: 'operator',
      autoConfirm: false,
      resolveBoundary: makeBoundaryResolver('shell_adjacent', {
        pauseAtFirstExecutionBoundary: scenario.shellFlow.pauseAtFirstExecutionBoundary === true,
        decisions: boundaryDecisions,
        recoveryEvents,
      }),
      onEvent: (event) => {
        timeline.push(mapOperatorEvent(event));
      },
    };

    const first = await orchestrator.runRequest(scenario.prompt, runOptions);
    outcomes.push(mapOutcome(first));
    recoveryEvents.push(...captureRecoveryEvents('shell_adjacent', first));

    if (first.status === 'paused' && scenario.shellFlow.pauseAtFirstExecutionBoundary) {
      const resumed = await orchestrator.resumeActiveRun({
        ...runOptions,
        resolveBoundary: makeBoundaryResolver('shell_adjacent', {
          pauseAtFirstExecutionBoundary: false,
          decisions: boundaryDecisions,
          recoveryEvents,
        }),
      });
      outcomes.push(mapOutcome(resumed));
      recoveryEvents.push(...captureRecoveryEvents('shell_adjacent', resumed));
    }

    if (scenario.shellFlow.injectConsistencyMismatch) {
      await injectConsistencyMismatch(cwd);
      timeline.push({
        type: 'consistency_injected',
        message: 'Injected runtime/orchestration mismatch for recovery validation.',
      });
      const inconsistent = await orchestrator.runRequest('continue current task flow', runOptions);
      outcomes.push(mapOutcome(inconsistent));
      recoveryEvents.push(...captureRecoveryEvents('shell_adjacent', inconsistent));

      const repaired = await orchestrator.runRequest('repair state and continue', {
        ...runOptions,
        autoConfirm: true,
      });
      outcomes.push(mapOutcome(repaired));
      recoveryEvents.push(...captureRecoveryEvents('shell_adjacent', repaired));
    }

    await runRecoveryFollowUp(orchestrator, 'shell_adjacent', runOptions, outcomes, recoveryEvents);

    return {
      ledger: await readLedger(cwd),
      outcomes,
      timeline,
      boundaryDecisions,
      recoveryEvents,
    };
  } finally {
    restoreEnv();
  }
}

async function runPlaintextFlow(
  cwd: string,
  scenario: ValidationScenarioDefinition,
): Promise<FlowExecutionArtifacts> {
  const timeline: ValidationTimelineEvent[] = [];
  const boundaryDecisions: ValidationBoundaryDecision[] = [];
  const recoveryEvents: ValidationRecoveryEvent[] = [];
  const outcomes: ValidationOutcomeSummary[] = [];
  const discoveryLogs: string[] = [];
  const restoreEnv = applyScenarioEnvOverrides(scenario.envOverrides);
  try {
    await applyProviderSetup(cwd, scenario);
    const discoveryReady = await ensureDiscoveryFoundation({
      cwd,
      prompt: scenario.prompt,
      interactive: false,
      autoApprove: scenario.oneShotFlow.autoApproveDiscovery,
      log: (message = '') => {
        discoveryLogs.push(String(message));
      },
    });

    timeline.push({
      type: 'discovery',
      message: discoveryReady
        ? 'Plain-text discovery resolved successfully.'
        : 'Plain-text discovery failed before execution.',
    });
    if (discoveryLogs.length > 0) {
      timeline.push({
        type: 'discovery_log',
        message: discoveryLogs.filter((entry) => entry.trim().length > 0).join(' | '),
      });
    }
    if (!discoveryReady) {
      return {
        ledger: await readLedger(cwd),
        outcomes,
        timeline,
        boundaryDecisions,
        recoveryEvents,
      };
    }

    const orchestrator = new ConversationalOrchestrator(cwd);
    const runOptions: OperatorRunOptions = {
      interactionMode: 'guide',
      autoConfirm: scenario.oneShotFlow.autoConfirmExecution,
      resolveBoundary: makeBoundaryResolver('plaintext_oneshot', {
        pauseAtFirstExecutionBoundary: false,
        decisions: boundaryDecisions,
        recoveryEvents,
      }),
      onEvent: (event) => {
        timeline.push(mapOperatorEvent(event));
      },
    };

    const first = await orchestrator.runRequest(scenario.prompt, runOptions);
    outcomes.push(mapOutcome(first));
    recoveryEvents.push(...captureRecoveryEvents('plaintext_oneshot', first));

    if (scenario.shellFlow.injectConsistencyMismatch) {
      await injectConsistencyMismatch(cwd);
      timeline.push({
        type: 'consistency_injected',
        message: 'Injected mismatch before one-shot recovery check.',
      });
      const repaired = await orchestrator.runRequest('repair state', {
        ...runOptions,
        autoConfirm: true,
      });
      outcomes.push(mapOutcome(repaired));
      recoveryEvents.push(...captureRecoveryEvents('plaintext_oneshot', repaired));
    }

    await runRecoveryFollowUp(orchestrator, 'plaintext_oneshot', runOptions, outcomes, recoveryEvents);

    return {
      ledger: await readLedger(cwd),
      outcomes,
      timeline,
      boundaryDecisions,
      recoveryEvents,
    };
  } finally {
    restoreEnv();
  }
}

async function buildScenarioReport(
  scenario: ValidationScenarioDefinition,
  flow: ValidationFlowKind,
  fixturePath: string,
  execution: FlowExecutionArtifacts,
): Promise<ValidationScenarioReport> {
  const nextSuggestedAction = execution.outcomes[execution.outcomes.length - 1]?.nextSuggestedAction;
  const restoreEnv = applyScenarioEnvOverrides(scenario.envOverrides);
  let provider: ValidationProviderSummary;
  try {
    provider = await summarizeProviderState(fixturePath);
  } finally {
    restoreEnv();
  }
  const report: ValidationScenarioReport = {
    scenario: scenario.name,
    flow,
    status: 'passed',
    fixturePath,
    foundation: summarizeFoundation(execution.ledger),
    qualitySignals: summarizeTaskQuality(execution.ledger),
    ledgerSnapshot: summarizeLedgerSnapshot(execution.ledger),
    outcomes: execution.outcomes,
    timeline: execution.timeline,
    boundaryDecisions: execution.boundaryDecisions,
    recoveryEvents: execution.recoveryEvents,
    provider,
    failures: [],
    warnings: [],
    ...(nextSuggestedAction ? { nextSuggestedAction } : {}),
  };

  const evaluation = evaluateScenarioFailures(report, scenario);
  report.failures = evaluation.failures;
  report.warnings = evaluation.warnings;
  report.status = report.failures.length === 0 ? 'passed' : 'failed';
  return report;
}

async function cleanupFixture(fixturePath: string, keepFixtures: boolean): Promise<void> {
  if (keepFixtures) {
    return;
  }
  await fs.rm(fixturePath, { recursive: true, force: true });
}

export async function runValidationScenarios(
  scenarios: ValidationScenarioDefinition[],
  options: ValidationHarnessOptions = {},
): Promise<ValidationRunReport> {
  const keepFixtures = options.keepFixtures ?? false;
  const reports: ValidationScenarioReport[] = [];

  for (const scenario of scenarios) {
    const shellFixture = await materializeScenarioFixture(scenario.fixtureName);
    try {
      const shellResult = await runShellAdjacentFlow(shellFixture, scenario);
      reports.push(await buildScenarioReport(scenario, 'shell_adjacent', shellFixture, shellResult));
    } finally {
      await cleanupFixture(shellFixture, keepFixtures);
    }

    const oneShotFixture = await materializeScenarioFixture(scenario.fixtureName);
    try {
      const oneShotResult = await runPlaintextFlow(oneShotFixture, scenario);
      reports.push(await buildScenarioReport(scenario, 'plaintext_oneshot', oneShotFixture, oneShotResult));
    } finally {
      await cleanupFixture(oneShotFixture, keepFixtures);
    }
  }

  return {
    generatedAt: new Date().toISOString(),
    reportVersion: 1,
    scenarioReports: reports,
    rankedFailures: rankFailures(reports),
  };
}

export async function runCanonicalValidationScenarios(
  options: ValidationHarnessOptions = {},
): Promise<ValidationRunReport> {
  return runValidationScenarios(CANONICAL_VALIDATION_SCENARIOS, options);
}

export function formatValidationReportMarkdown(report: ValidationRunReport): string {
  const lines: string[] = [];
  lines.push('# Scrimble Scenario Validation Report');
  lines.push('');
  lines.push(`Generated: ${report.generatedAt}`);
  lines.push('');
  lines.push('## Scenario Runs');
  lines.push('');
  lines.push('| Scenario | Flow | Status | Provider health | Failures | Warnings | Next action |');
  lines.push('| --- | --- | --- | --- | ---: | ---: | --- |');
  for (const scenarioReport of report.scenarioReports) {
    const providerHealth = scenarioReport.provider.hasActiveProfile
      ? `${scenarioReport.provider.provider ?? '-'} / ${scenarioReport.provider.usableNow ? 'usable' : 'unusable'}`
      : 'no-profile';
    lines.push(
      `| ${scenarioReport.scenario} | ${scenarioReport.flow} | ${scenarioReport.status} | ${providerHealth} | ${scenarioReport.failures.length} | ${scenarioReport.warnings.length} | ${scenarioReport.nextSuggestedAction ?? '-'} |`,
    );
  }
  lines.push('');
  lines.push('## Ranked Failures');
  lines.push('');
  if (report.rankedFailures.length === 0) {
    lines.push('No failures detected.');
    lines.push('');
    return `${lines.join('\n')}\n`;
  }
  lines.push('| Category | Count | Highest severity | Scenarios |');
  lines.push('| --- | ---: | --- | --- |');
  for (const ranked of report.rankedFailures) {
    lines.push(`| ${ranked.category} | ${ranked.count} | ${ranked.highestSeverity} | ${ranked.scenarios.join(', ')} |`);
  }
  lines.push('');
  return `${lines.join('\n')}\n`;
}

export async function writeValidationReport(
  report: ValidationRunReport,
  outputDir?: string,
): Promise<{ directory: string; jsonPath: string; markdownPath: string }> {
  const directory = outputDir ?? path.join(os.tmpdir(), `scrimble-validation-report-${Date.now()}`);
  await fs.mkdir(directory, { recursive: true });
  const jsonPath = path.join(directory, 'validation-report.json');
  const markdownPath = path.join(directory, 'validation-report.md');
  await fs.writeFile(jsonPath, `${JSON.stringify(report, null, 2)}\n`, 'utf8');
  await fs.writeFile(markdownPath, formatValidationReportMarkdown(report), 'utf8');
  return {
    directory,
    jsonPath,
    markdownPath,
  };
}
