import React, { useCallback, useMemo, useRef, useState } from 'react';
import { Box, Text, useApp, useInput } from 'ink';
import type { DiscoveryMode, InteractionMode, Intent } from '@scrimble/shared';
import { getDefaultApiKeyPlaceholder, getDefaultModel } from '../../lib/ai/provider.js';
import { getDefaultAuthStrategy, providerSupportsAutoModel } from '../../lib/ai/provider-catalog.js';
import type {
  AgentSetupInput,
  OperatorBoundary,
  OperatorBoundaryResolution,
  OperatorEvent,
  OperatorRunOptions,
  OperatorRunResult,
} from '../../lib/agent/types.js';
import {
  approveFoundation,
  buildAutogeneratedFoundation,
  buildCustomFoundation,
  buildInteractiveFoundation,
  persistDiscoveryDraft,
  persistDiscoveryProgress,
  skipFoundation,
  type FoundationAnswers,
} from '../../lib/discovery/foundation.js';
import { ApprovalCard } from './ApprovalCard.js';
import { Composer } from './Composer.js';
import { EnvironmentStrip } from './EnvironmentStrip.js';
import { FooterHints } from './FooterHints.js';
import { HeroCard } from './HeroCard.js';
import { TranscriptPane } from './TranscriptPane.js';
import type { StartupContext, TranscriptEntry } from './types.js';

const MAX_TRANSCRIPT_ENTRIES = 300;

function nextId(): string {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

function boundaryDetails(boundary: OperatorBoundary): string[] {
  return [
    boundary.reason,
    ...(boundary.category ? [`Category: ${boundary.category}`] : []),
    ...(boundary.riskLevel ? [`Risk: ${boundary.riskLevel}`] : []),
    `Scope: parallel=${boundary.scope.parallel}, maxTasks=${boundary.scope.maxTasks}`,
    ...(boundary.nextStepHint ? [`If approved: ${boundary.nextStepHint}`] : []),
  ];
}

const DISCOVERY_QUALITY_OPTIONS = ['prototype', 'production', 'enterprise'] as const;
const DISCOVERY_TIMELINE_OPTIONS = ['asap', 'flexible', 'long_term'] as const;

const INTERACTIVE_QUESTIONS: Array<{
  field: keyof FoundationAnswers;
  prompt: string;
}> = [
  { field: 'projectName', prompt: 'Project name' },
  { field: 'goal', prompt: 'Core goal / product objective' },
  { field: 'productVision', prompt: 'Product vision statement' },
  { field: 'targetUsers', prompt: 'Target users' },
  { field: 'successCriteria', prompt: 'Success criteria (semicolon-separated)' },
  { field: 'nonGoals', prompt: 'Non-goals / out-of-scope (semicolon-separated)' },
  { field: 'qualityPreference', prompt: 'Quality bar (prototype|production|enterprise)' },
  { field: 'timeline', prompt: 'Timeline preference (asap|flexible|long_term)' },
  { field: 'productConstraints', prompt: 'Product constraints (semicolon-separated)' },
  { field: 'technicalConstraints', prompt: 'Technical constraints (semicolon-separated)' },
  { field: 'designDirection', prompt: 'Design / UX direction (optional)' },
];

function parseListValue(input: string): string[] {
  return [...new Set(
    input
      .split(/\r?\n|;/)
      .map((entry) => entry.trim())
      .filter((entry) => entry.length > 0),
  )];
}

function normalizeInteractiveField(
  answers: Partial<FoundationAnswers>,
  field: keyof FoundationAnswers,
  rawValue: string,
): Partial<FoundationAnswers> {
  const trimmed = rawValue.trim();
  if (field === 'successCriteria' || field === 'nonGoals' || field === 'productConstraints' || field === 'technicalConstraints') {
    return { ...answers, [field]: parseListValue(trimmed) };
  }
  if (field === 'qualityPreference') {
    const selected = DISCOVERY_QUALITY_OPTIONS.find((entry) => entry === trimmed.toLowerCase()) ?? 'production';
    return { ...answers, qualityPreference: selected };
  }
  if (field === 'timeline') {
    const selected = DISCOVERY_TIMELINE_OPTIONS.find((entry) => entry === trimmed.toLowerCase()) ?? 'flexible';
    return { ...answers, timeline: selected };
  }
  return { ...answers, [field]: trimmed };
}

function draftToAnswers(intent: Intent | undefined): Partial<FoundationAnswers> {
  if (!intent) {
    return {};
  }
  return {
    projectName: intent.projectName,
    goal: intent.goal,
    productVision: intent.productVision,
    targetUsers: intent.targetUsers,
    successCriteria: intent.successCriteria,
    nonGoals: intent.nonGoals,
    qualityPreference: intent.qualityPreference,
    timeline: intent.timeline,
    productConstraints: intent.productConstraints,
    technicalConstraints: intent.technicalConstraints,
    ...(intent.designDirection ? { designDirection: intent.designDirection } : {}),
  };
}

function toFoundationAnswers(
  answers: Partial<FoundationAnswers>,
  startup: StartupContext,
  draftIntent?: Intent,
): FoundationAnswers {
  const fallback = draftIntent ?? startup.discoveryDraft;
  return {
    projectName: String(answers.projectName ?? startup.discoveryScan?.repoName ?? startup.repoName),
    goal: String(answers.goal ?? fallback?.goal ?? 'Define project goal'),
    productVision: String(answers.productVision ?? answers.goal ?? fallback?.productVision ?? 'Define product vision'),
    targetUsers: String(answers.targetUsers ?? fallback?.targetUsers ?? 'Primary users'),
    successCriteria: answers.successCriteria ?? fallback?.successCriteria ?? ['Core workflow works end-to-end'],
    nonGoals: answers.nonGoals ?? fallback?.nonGoals ?? ['Do not rewrite unrelated modules'],
    qualityPreference: answers.qualityPreference ?? fallback?.qualityPreference ?? 'production',
    timeline: answers.timeline ?? fallback?.timeline ?? 'flexible',
    productConstraints: answers.productConstraints ?? fallback?.productConstraints ?? [],
    technicalConstraints: answers.technicalConstraints ?? fallback?.technicalConstraints ?? [],
    ...(answers.designDirection ? { designDirection: answers.designDirection } : {}),
  };
}

export function buildStartupTranscript(startup: StartupContext): TranscriptEntry[] {
  const entries: TranscriptEntry[] = [
    {
      id: nextId(),
      kind: 'startup',
      message: `Workspace: ${startup.repoPath}`,
    },
  ];

  if (!startup.hasConfig) {
    entries.push({
      id: nextId(),
      kind: 'startup',
      message: 'AI provider profiles are missing. Press Ctrl+G to open setup studio.',
    });
  } else if (!startup.profileValid) {
    entries.push({
      id: nextId(),
      kind: 'startup',
      message: 'Active provider profile is invalid. Press Ctrl+G to fix provider/model/auth setup.',
    });
  }

  if (!startup.foundationReady) {
    entries.push({
      id: nextId(),
      kind: 'startup',
      message: 'Project foundation is not approved yet. Discovery will run before normal execution.',
    });
    if (startup.discoveryScan) {
      entries.push({
        id: nextId(),
        kind: 'startup',
        message: `Scan: ${startup.discoveryScan.projectType} repo, ${startup.discoveryScan.languages.join(', ') || 'unknown language'}${startup.discoveryScan.frameworks.length > 0 ? `, frameworks: ${startup.discoveryScan.frameworks.join(', ')}` : ''}.`,
      });
    }
    if (startup.discoveryStep) {
      entries.push({
        id: nextId(),
        kind: 'startup',
        message: `Resuming discovery at: ${startup.discoveryStep}.`,
      });
    }
    if (!startup.discoveryStep || startup.discoveryStep === 'scan_summary' || startup.discoveryStep === 'mode_selection') {
      entries.push({
        id: nextId(),
        kind: 'system',
        message: 'Choose discovery mode: `interactive`, `autogenerate`, `custom`, or `skip`.',
      });
    } else if (startup.discoveryStep === 'autogenerate_goal') {
      entries.push({
        id: nextId(),
        kind: 'system',
        message: 'Provide the core goal to autogenerate the project foundation.',
      });
    } else if (startup.discoveryStep === 'custom_brief') {
      entries.push({
        id: nextId(),
        kind: 'system',
        message: 'Provide your custom project brief in one message.',
      });
    } else if (startup.discoveryStep === 'interactive_questions') {
      const index = startup.discoveryQuestionIndex ?? 0;
      const question = INTERACTIVE_QUESTIONS[index];
      if (question) {
        entries.push({
          id: nextId(),
          kind: 'system',
          message: `Discovery question ${index + 1}/${INTERACTIVE_QUESTIONS.length}: ${question.prompt}`,
        });
      }
    } else if (startup.discoveryStep === 'draft_review') {
      entries.push({
        id: nextId(),
        kind: 'system',
        message: 'Review actions: type `approve`, `edit`, `regenerate`, or `skip`.',
      });
    }
  }

  if (startup.recoveryState === 'inconsistent' && startup.recoveryMessage) {
    entries.push({
      id: nextId(),
      kind: 'blocked',
      message: `State mismatch detected: ${startup.recoveryMessage}`,
    });
  } else if (startup.recoveryState === 'pending_approval' && startup.pendingBoundary) {
    entries.push({
      id: nextId(),
      kind: 'approval_needed',
      message: `Pending approval: ${startup.pendingBoundary.actionSummary}`,
      details: boundaryDetails(startup.pendingBoundary),
    });
  } else if (startup.recoveryState === 'blocked' && startup.blockedTaskId) {
    entries.push({
      id: nextId(),
      kind: 'blocked',
      message: `Blocked task: ${startup.blockedTaskId}`,
      details: startup.blockedTaskReason ? [startup.blockedTaskReason] : undefined,
    });
  } else if (startup.recoveryState === 'failed' && startup.failedTaskId) {
    entries.push({
      id: nextId(),
      kind: 'error',
      message: `Failed task: ${startup.failedTaskId}`,
      details: startup.failedTaskReason ? [startup.failedTaskReason] : undefined,
    });
  }

  if (startup.activeExecutionTaskId) {
    entries.push({
      id: nextId(),
      kind: 'startup',
      message: `Active execution: ${startup.activeExecutionTaskId} (${startup.activeExecutionPhase ?? 'executing'})`,
      details: startup.activeExecutionStatusMessage ? [startup.activeExecutionStatusMessage] : undefined,
    });
  }
  if (startup.lastCompletedStep) {
    entries.push({
      id: nextId(),
      kind: 'startup',
      message: `Last completed step: ${startup.lastCompletedStep}`,
    });
  }

  if (startup.recoveryActions.length > 0) {
    entries.push({
      id: nextId(),
      kind: 'system',
      message: 'Available recovery actions:',
      details: startup.recoveryActions.map((action) => `${action.label}: ${action.description}`),
    });
  }

  if (startup.activeRunRequest) {
    entries.push({
      id: nextId(),
      kind: 'startup',
      message: `Active run found: ${startup.activeRunRequest}`,
    });
    if (startup.pendingBoundary) {
      entries.push({
        id: nextId(),
        kind: 'approval_needed',
        message: startup.pendingBoundary.actionSummary,
        details: boundaryDetails(startup.pendingBoundary),
      });
    } else if (startup.lastPauseReason) {
      entries.push({
        id: nextId(),
        kind: 'paused',
        message: startup.lastPauseReason,
      });
    }
  } else if (startup.lastOutcomeSummary) {
    entries.push({
      id: nextId(),
      kind: 'startup',
      message: `Last outcome (${startup.lastOutcomeStatus ?? 'unknown'}): ${startup.lastOutcomeSummary}`,
    });
  }

  if (startup.recentOutcomes.length > 0) {
    entries.push({
      id: nextId(),
      kind: 'startup',
      message: 'Recent run history:',
      details: startup.recentOutcomes.slice(0, 3).map((outcome) =>
        `${outcome.status} • ${outcome.request} • ${outcome.summary}`),
    });
  }

  return entries;
}

export function mapOperatorEventToTranscript(event: OperatorEvent): TranscriptEntry | null {
  switch (event.type) {
    case 'planning':
      return { id: nextId(), kind: 'agent_summary', message: 'Inspecting context and choosing the next step.' };
    case 'resumed':
      return { id: nextId(), kind: 'system', message: event.message };
    case 'step_started':
      return { id: nextId(), kind: 'step_started', message: event.message };
    case 'step_completed':
      return {
        id: nextId(),
        kind: 'step_completed',
        message: event.message,
        details: event.result?.details,
      };
    case 'boundary_requested':
      return event.boundary
        ? {
          id: nextId(),
          kind: 'approval_needed',
          message: event.boundary.actionSummary,
          details: boundaryDetails(event.boundary),
        }
        : { id: nextId(), kind: 'approval_needed', message: event.message };
    case 'redirected':
      return { id: nextId(), kind: 'system', message: event.message };
    case 'paused':
      return {
        id: nextId(),
        kind: 'paused',
        message: event.summary ?? event.message,
        details: [
          ...(event.reason ? [event.reason] : []),
          ...(event.recoveryActions?.map((action) => `${action.label}: ${action.description}`) ?? []),
        ],
      };
    case 'blocked':
      return {
        id: nextId(),
        kind: 'blocked',
        message: event.summary ?? event.message,
        details: [
          ...(event.reason ? [event.reason] : []),
          ...(event.lastFailure?.detail ? [event.lastFailure.detail] : []),
          ...(event.recoveryActions?.map((action) => `${action.label}: ${action.description}`) ?? []),
        ],
      };
    case 'completed':
      return { id: nextId(), kind: 'completed', message: event.summary ?? event.message };
    default:
      return null;
  }
}

export function mapRunOutcomeToTranscript(result: OperatorRunResult): TranscriptEntry {
  const details = [
    ...(result.reason ? [result.reason] : []),
    ...(result.lastFailure?.taskId ? [`Task: ${result.lastFailure.taskId}`] : []),
    ...(result.lastFailure?.detail ? [result.lastFailure.detail] : []),
    ...(result.recoveryActions && result.recoveryActions.length > 0
      ? [
          'Recovery actions:',
          ...result.recoveryActions.map((action) => `- ${action.label}: ${action.description}`),
        ]
      : []),
  ];
  switch (result.status) {
    case 'completed':
      return { id: nextId(), kind: 'completed', message: result.summary };
    case 'paused':
      return {
        id: nextId(),
        kind: 'paused',
        message: result.summary,
        details: details.length > 0 ? details : undefined,
      };
    case 'blocked':
      return {
        id: nextId(),
        kind: 'blocked',
        message: result.summary,
        details: details.length > 0 ? details : undefined,
      };
    case 'failed':
      return {
        id: nextId(),
        kind: 'error',
        message: result.summary,
        details: details.length > 0 ? details : undefined,
      };
    case 'redirected':
      return { id: nextId(), kind: 'system', message: result.summary };
    default:
      return { id: nextId(), kind: 'agent_summary', message: result.summary };
  }
}

function appendTranscript(
  setTranscript: React.Dispatch<React.SetStateAction<TranscriptEntry[]>>,
  entry: TranscriptEntry,
): void {
  setTranscript((previous) => {
    const next = [...previous, entry];
    if (next.length <= MAX_TRANSCRIPT_ENTRIES) {
      return next;
    }
    return next.slice(next.length - MAX_TRANSCRIPT_ENTRIES);
  });
}

export interface OperatorShellProps {
  startup: StartupContext;
  initialMode: InteractionMode;
  autoConfirm: boolean;
  initialVerbose: boolean;
  setupSeed: AgentSetupInput;
  runRequest: (request: string, options: OperatorRunOptions) => Promise<OperatorRunResult>;
  resumeActiveRun: (options: OperatorRunOptions) => Promise<OperatorRunResult>;
  onExitAction?: (action: 'exit' | 'configure_providers') => void;
}

export function OperatorShell({
  startup,
  initialMode,
  autoConfirm,
  initialVerbose,
  setupSeed,
  runRequest,
  resumeActiveRun,
  onExitAction,
}: OperatorShellProps): JSX.Element {
  const { exit } = useApp();
  const rows = process.stdout.rows ?? 40;
  const [draft, setDraft] = useState('');
  const [busy, setBusy] = useState(false);
  const [showDetails, setShowDetails] = useState(initialVerbose);
  const [discoveryRequired, setDiscoveryRequired] = useState(!startup.foundationReady);
  const [discoveryMode, setDiscoveryMode] = useState<DiscoveryMode | undefined>(startup.discoveryMode);
  const [discoveryStep, setDiscoveryStep] = useState(startup.discoveryStep ?? 'mode_selection');
  const [discoveryQuestionIndex, setDiscoveryQuestionIndex] = useState(startup.discoveryQuestionIndex ?? 0);
  const [discoveryAnswers, setDiscoveryAnswers] = useState<Partial<FoundationAnswers>>(() => draftToAnswers(startup.discoveryDraft));
  const [discoveryDraft, setDiscoveryDraft] = useState<Intent | undefined>(startup.discoveryDraft);
  const [activeRequest, setActiveRequest] = useState<string | undefined>(startup.activeRunRequest);
  const [latestActivity, setLatestActivity] = useState<string | undefined>(startup.recoveryMessage ?? startup.lastOutcomeSummary);
  const [nextAction, setNextAction] = useState<string | undefined>(
    startup.recoveryActions[0]?.label ?? (startup.pendingBoundary ? 'Resolve approval boundary.' : undefined),
  );
  const [resumeAvailable, setResumeAvailable] = useState(
    startup.recoveryState === 'resumable' || startup.recoveryState === 'pending_approval' || Boolean(startup.activeRunRequest),
  );
  const [pendingBoundary, setPendingBoundary] = useState<OperatorBoundary | undefined>(startup.pendingBoundary);
  const [recoveryState, setRecoveryState] = useState(startup.recoveryState);
  const [recoveryMessage, setRecoveryMessage] = useState<string | undefined>(startup.recoveryMessage);
  const [availableRecoveryActions, setAvailableRecoveryActions] = useState(startup.recoveryActions);
  const [recentOutcomes, setRecentOutcomes] = useState(startup.recentOutcomes);
  const [transcript, setTranscript] = useState<TranscriptEntry[]>(() => buildStartupTranscript(startup));
  const modeRef = useRef<InteractionMode>(initialMode);
  const setupRef = useRef<AgentSetupInput>({ ...setupSeed, interactionMode: initialMode });
  const boundaryResolverRef = useRef<((resolution: OperatorBoundaryResolution) => void) | null>(null);

  const ensureConfigureSetup = useCallback((boundary: OperatorBoundary): void => {
    if (boundary.action !== 'configure_ai') {
      return;
    }
    const provider = setupRef.current.provider ?? startup.provider ?? 'openai';
    const modelStrategy = setupRef.current.modelStrategy
      ?? startup.modelStrategy
      ?? (providerSupportsAutoModel(provider) ? 'auto' : 'explicit');
    const authStrategy = setupRef.current.authStrategy ?? getDefaultAuthStrategy(provider, true);
    const model = modelStrategy === 'explicit'
      ? (setupRef.current.model ?? startup.model ?? getDefaultModel(provider))
      : undefined;
    const apiKey = authStrategy === 'api_key'
      ? setupRef.current.apiKey ?? getDefaultApiKeyPlaceholder(provider)
      : setupRef.current.apiKey;
    const token = authStrategy === 'personal_access_token'
      ? setupRef.current.token ?? setupRef.current.apiKey
      : setupRef.current.token;
    setupRef.current = {
      ...setupRef.current,
      provider,
      modelStrategy,
      ...(model ? { model } : {}),
      authStrategy,
      ...(apiKey ? { apiKey } : {}),
      ...(token ? { token } : {}),
      interactionMode: modeRef.current,
    };
  }, [startup.model, startup.modelStrategy, startup.provider]);

  const resolveBoundary = useCallback((resolution: OperatorBoundaryResolution): void => {
    const resolver = boundaryResolverRef.current;
    if (!resolver) {
      return;
    }
    resolver(resolution);
    boundaryResolverRef.current = null;
    if (resolution.kind !== 'proceed') {
      setPendingBoundary(undefined);
    }
  }, []);

  const runOperator = useCallback(async (request?: string): Promise<void> => {
    setBusy(true);
    if (request) {
      setActiveRequest(request);
      setResumeAvailable(false);
    }

    const runOptions: OperatorRunOptions = {
      setup: setupRef.current,
      interactionMode: modeRef.current,
      autoConfirm,
      resolveBoundary: async (boundary) => {
        setPendingBoundary(boundary);
        setNextAction('Approve, pause, or redirect this boundary.');
        setRecoveryState('pending_approval');
        setRecoveryMessage(boundary.reason);
        setAvailableRecoveryActions([
          { kind: 'pending_approval', label: 'Approve boundary', description: 'Proceed with the requested action.' },
          { kind: 'show_plan', label: 'Inspect plan', description: 'Inspect plan rationale/scope before approving.' },
          { kind: 'inspect_logs', label: 'Inspect logs', description: 'Inspect recent logs before deciding.' },
        ]);
        appendTranscript(setTranscript, {
          id: nextId(),
          kind: 'approval_needed',
          message: boundary.actionSummary,
          details: boundaryDetails(boundary),
        });

        if (autoConfirm) {
          ensureConfigureSetup(boundary);
          return { kind: 'proceed' };
        }

        return new Promise<OperatorBoundaryResolution>((resolve) => {
          boundaryResolverRef.current = (resolution) => {
            if (resolution.kind === 'proceed') {
              ensureConfigureSetup(boundary);
            }
            resolve(resolution);
          };
        });
      },
      onEvent: (event) => {
        const entry = mapOperatorEventToTranscript(event);
        if (entry) {
          appendTranscript(setTranscript, entry);
        }
        if (event.type === 'step_started') {
          setLatestActivity(`Starting: ${event.message}`);
        } else if (event.type === 'step_completed') {
          setLatestActivity(`Completed: ${event.message}`);
        } else if (event.type === 'boundary_requested' && event.boundary) {
          setPendingBoundary(event.boundary);
          setRecoveryState('pending_approval');
          setRecoveryMessage(event.boundary.reason);
          if (event.recoveryActions) {
            setAvailableRecoveryActions(event.recoveryActions);
          }
        } else if (event.type === 'blocked' || event.type === 'paused' || event.type === 'completed') {
          setLatestActivity(event.summary ?? event.message);
          setRecoveryMessage(event.reason ?? event.summary ?? event.message);
          if (event.type === 'blocked') {
            setRecoveryState('blocked');
          } else if (event.type === 'paused') {
            setRecoveryState('resumable');
          } else {
            setRecoveryState('completed');
          }
          if (event.recoveryActions) {
            setAvailableRecoveryActions(event.recoveryActions);
          }
        }
      },
    };

    try {
      const result = request
        ? await runRequest(request, runOptions)
        : await resumeActiveRun(runOptions);
      appendTranscript(setTranscript, mapRunOutcomeToTranscript(result));
      setLatestActivity(result.summary);
      setNextAction(result.nextSuggestedAction ?? result.recoveryActions?.[0]?.label);
      setPendingBoundary(result.boundary);
      setResumeAvailable(result.status === 'paused');
      setRecoveryMessage(result.reason ?? result.summary);
      setAvailableRecoveryActions(result.recoveryActions ?? []);
      setRecoveryState(
        result.recoveryKind === 'state_inconsistent'
          ? 'inconsistent'
          : result.status === 'blocked'
            ? 'blocked'
            : result.status === 'failed'
              ? 'failed'
              : result.status === 'completed'
                ? 'completed'
                : result.boundary
                  ? 'pending_approval'
                  : 'resumable',
      );
      setRecentOutcomes((previous) => [
        {
          status: result.status,
          request: result.lastRequest,
          summary: result.summary,
          completedAt: new Date().toISOString(),
        },
        ...previous,
      ].slice(0, 5));
    } catch (error) {
      appendTranscript(setTranscript, {
        id: nextId(),
        kind: 'error',
        message: error instanceof Error ? error.message : String(error),
      });
      setLatestActivity('Run failed');
      setNextAction('Review the error and send a new request.');
      setRecoveryState('failed');
      setRecoveryMessage(error instanceof Error ? error.message : String(error));
    } finally {
      setBusy(false);
    }
  }, [autoConfirm, ensureConfigureSetup, resumeActiveRun, runRequest]);

  const runSteeringAction = useCallback(async (action: string): Promise<void> => {
    if (busy) {
      return;
    }

    if (action === 'resume') {
      if (!resumeAvailable) {
        return;
      }
      appendTranscript(setTranscript, { id: nextId(), kind: 'system', message: 'Steering: resume active run.' });
      await runOperator();
      return;
    }

    if (action === 'retry') {
      appendTranscript(setTranscript, { id: nextId(), kind: 'system', message: 'Steering: retry current task.' });
      await runOperator('retry the current failed or blocked task and continue with one bounded step');
      return;
    }

    if (action === 'replan') {
      appendTranscript(setTranscript, { id: nextId(), kind: 'system', message: 'Steering: replan from current state.' });
      await runOperator('replan from current state and regenerate the task graph');
      return;
    }

    if (action === 'show_plan') {
      appendTranscript(setTranscript, { id: nextId(), kind: 'system', message: 'Steering: inspect current plan.' });
      await runOperator('show current plan with rationale, scope, dependencies, verification, and warnings');
      return;
    }

    if (action === 'inspect_failure') {
      appendTranscript(setTranscript, { id: nextId(), kind: 'system', message: 'Steering: inspect latest failure context.' });
      await runOperator('show the latest failure details including files, commands, and recommended recovery actions');
      return;
    }

    if (action === 'inspect_logs') {
      appendTranscript(setTranscript, { id: nextId(), kind: 'system', message: 'Steering: inspect runtime logs.' });
      await runOperator('show recent runtime logs and summarize blockers');
      return;
    }

    if (action === 'repair_state') {
      appendTranscript(setTranscript, { id: nextId(), kind: 'system', message: 'Steering: repair runtime/orchestration consistency.' });
      await runOperator('repair runtime and orchestration state consistency');
      return;
    }

    if (action === 'revise_foundation') {
      if (startup.discoveryScan) {
        await persistDiscoveryProgress(
          startup.repoPath,
          discoveryMode ?? 'interactive',
          'mode_selection',
          startup.discoveryScan,
          discoveryDraft,
          0,
        );
      }
      appendTranscript(setTranscript, {
        id: nextId(),
        kind: 'system',
        message: 'Steering: returning to foundation discovery. Choose mode: interactive|autogenerate|custom|skip.',
      });
      setDiscoveryRequired(true);
      setDiscoveryStep('mode_selection');
      setDiscoveryMode(discoveryMode ?? 'interactive');
      setDiscoveryQuestionIndex(0);
      setRecoveryState('idle');
      setRecoveryMessage(undefined);
      setAvailableRecoveryActions([]);
      setDraft('');
      return;
    }

    if (action === 'dismiss_completed') {
      setResumeAvailable(false);
      setActiveRequest(undefined);
      setLatestActivity('Completed run dismissed.');
      setNextAction('Type a new request to continue.');
      setRecoveryState('idle');
      setRecoveryMessage(undefined);
      setAvailableRecoveryActions([]);
      appendTranscript(setTranscript, { id: nextId(), kind: 'system', message: 'Dismissed completed run context.' });
    }
  }, [busy, discoveryDraft, discoveryMode, resumeAvailable, runOperator, startup.discoveryScan, startup.repoPath]);

  const promptDiscoveryQuestion = useCallback((index: number): void => {
    const next = INTERACTIVE_QUESTIONS[index];
    if (!next) {
      return;
    }
    appendTranscript(setTranscript, {
      id: nextId(),
      kind: 'system',
      message: `Discovery question ${index + 1}/${INTERACTIVE_QUESTIONS.length}: ${next.prompt}`,
    });
  }, []);

  const submitDiscovery = useCallback(async (input: string): Promise<void> => {
    const scan = startup.discoveryScan;
    if (!scan) {
      appendTranscript(setTranscript, {
        id: nextId(),
        kind: 'error',
        message: 'Discovery scan context is unavailable. Restart the shell to retry discovery.',
      });
      return;
    }

    const value = input.trim();

    if (discoveryStep === 'draft_review' && discoveryDraft) {
      const decision = value.toLowerCase();
      if (decision === 'approve' || decision === 'a') {
        await approveFoundation(startup.repoPath, discoveryDraft, discoveryMode ?? 'autogenerate', scan);
        appendTranscript(setTranscript, {
          id: nextId(),
          kind: 'completed',
          message: 'Project foundation approved. Discovery complete.',
        });
        setDiscoveryRequired(false);
        setNextAction('Project foundation approved. You can now start normal execution.');
        return;
      }
      if (decision === 'skip') {
        await skipFoundation(startup.repoPath);
        appendTranscript(setTranscript, {
          id: nextId(),
          kind: 'paused',
          message: 'Project foundation was explicitly skipped. Normal execution is now enabled.',
        });
        setDiscoveryRequired(false);
        setNextAction('Foundation skipped. You can continue with normal execution.');
        return;
      }
      if (decision === 'edit') {
        setDiscoveryMode('interactive');
        setDiscoveryStep('interactive_questions');
        setDiscoveryQuestionIndex(0);
        const draftAnswers = draftToAnswers(discoveryDraft);
        setDiscoveryAnswers(draftAnswers);
        await persistDiscoveryProgress(startup.repoPath, 'interactive', 'interactive_questions', scan, discoveryDraft, 0);
        promptDiscoveryQuestion(0);
        return;
      }
      if (decision === 'regenerate') {
        setDiscoveryStep('autogenerate_goal');
        await persistDiscoveryProgress(startup.repoPath, discoveryMode ?? 'autogenerate', 'autogenerate_goal', scan, discoveryDraft);
        appendTranscript(setTranscript, {
          id: nextId(),
          kind: 'system',
          message: 'Provide a fresh core goal to regenerate the foundation draft.',
        });
        return;
      }

      appendTranscript(setTranscript, {
        id: nextId(),
        kind: 'system',
        message: 'Review actions: type `approve`, `edit`, `regenerate`, or `skip`.',
      });
      return;
    }

    if (!discoveryMode || discoveryStep === 'mode_selection' || discoveryStep === 'scan_summary') {
      const normalized = value.toLowerCase();
      if (normalized === 'skip') {
        await skipFoundation(startup.repoPath);
        appendTranscript(setTranscript, {
          id: nextId(),
          kind: 'paused',
          message: 'Project foundation was skipped by user choice.',
        });
        setDiscoveryRequired(false);
        return;
      }
      const selectedMode: DiscoveryMode | undefined = normalized.startsWith('i')
        ? 'interactive'
        : normalized.startsWith('a')
          ? 'autogenerate'
          : normalized.startsWith('c')
            ? 'custom'
            : undefined;
      if (!selectedMode) {
        appendTranscript(setTranscript, {
          id: nextId(),
          kind: 'system',
          message: 'Choose discovery mode: `interactive`, `autogenerate`, `custom`, or `skip`.',
        });
        return;
      }
      setDiscoveryMode(selectedMode);
      if (selectedMode === 'interactive') {
        setDiscoveryStep('interactive_questions');
        setDiscoveryQuestionIndex(0);
        await persistDiscoveryProgress(startup.repoPath, selectedMode, 'interactive_questions', scan, discoveryDraft, 0);
        promptDiscoveryQuestion(0);
        return;
      }
      if (selectedMode === 'custom') {
        setDiscoveryStep('custom_brief');
        await persistDiscoveryProgress(startup.repoPath, selectedMode, 'custom_brief', scan, discoveryDraft);
        appendTranscript(setTranscript, {
          id: nextId(),
          kind: 'system',
          message: 'Paste your custom project brief in one message, then press Enter.',
        });
        return;
      }

      setDiscoveryStep('autogenerate_goal');
      await persistDiscoveryProgress(startup.repoPath, selectedMode, 'autogenerate_goal', scan, discoveryDraft);
      appendTranscript(setTranscript, {
        id: nextId(),
        kind: 'system',
        message: 'Provide the core goal to autogenerate the project foundation.',
      });
      return;
    }

    if (discoveryStep === 'autogenerate_goal') {
      const draft = await buildAutogeneratedFoundation(
        startup.repoPath,
        scan,
        value || discoveryDraft?.goal || startup.discoveryDraft?.goal || 'Define project goal',
        discoveryDraft ?? startup.discoveryDraft,
      );
      setDiscoveryDraft(draft);
      setDiscoveryStep('draft_review');
      await persistDiscoveryDraft(startup.repoPath, draft, discoveryMode ?? 'autogenerate', scan);
      appendTranscript(setTranscript, {
        id: nextId(),
        kind: 'agent_summary',
        message: `Draft ready for ${draft.projectName}. Goal: ${draft.goal}`,
        details: [
          `Target users: ${draft.targetUsers}`,
          `Quality bar: ${draft.qualityPreference}`,
          `Timeline: ${draft.timeline}`,
        ],
      });
      appendTranscript(setTranscript, {
        id: nextId(),
        kind: 'system',
        message: 'Type `approve`, `edit`, `regenerate`, or `skip`.',
      });
      return;
    }

    if (discoveryStep === 'custom_brief') {
      const draft = await buildCustomFoundation(startup.repoPath, scan, value, discoveryDraft ?? startup.discoveryDraft);
      setDiscoveryDraft(draft);
      setDiscoveryStep('draft_review');
      await persistDiscoveryDraft(startup.repoPath, draft, discoveryMode ?? 'custom', scan);
      appendTranscript(setTranscript, {
        id: nextId(),
        kind: 'agent_summary',
        message: `Custom brief normalized into foundation draft for ${draft.projectName}.`,
      });
      appendTranscript(setTranscript, {
        id: nextId(),
        kind: 'system',
        message: 'Type `approve`, `edit`, `regenerate`, or `skip`.',
      });
      return;
    }

    if (discoveryStep === 'interactive_questions') {
      const question = INTERACTIVE_QUESTIONS[discoveryQuestionIndex];
      if (!question) {
        const finalized = toFoundationAnswers(discoveryAnswers, startup, discoveryDraft);
        const draft = await buildInteractiveFoundation(startup.repoPath, scan, finalized, discoveryDraft ?? startup.discoveryDraft);
        setDiscoveryDraft(draft);
        setDiscoveryStep('draft_review');
        await persistDiscoveryDraft(startup.repoPath, draft, discoveryMode ?? 'interactive', scan);
        appendTranscript(setTranscript, {
          id: nextId(),
          kind: 'agent_summary',
          message: 'Interactive foundation draft is ready for review.',
        });
        appendTranscript(setTranscript, {
          id: nextId(),
          kind: 'system',
          message: 'Type `approve`, `edit`, `regenerate`, or `skip`.',
        });
        return;
      }

      const mergedAnswers = normalizeInteractiveField(discoveryAnswers, question.field, value);
      setDiscoveryAnswers(mergedAnswers);
      const nextQuestionIndex = discoveryQuestionIndex + 1;
      setDiscoveryQuestionIndex(nextQuestionIndex);
      await persistDiscoveryProgress(
        startup.repoPath,
        discoveryMode ?? 'interactive',
        'interactive_questions',
        scan,
        discoveryDraft,
        nextQuestionIndex,
      );

      const nextQuestion = INTERACTIVE_QUESTIONS[nextQuestionIndex];
      if (nextQuestion) {
        promptDiscoveryQuestion(nextQuestionIndex);
        return;
      }

      const finalized = toFoundationAnswers(mergedAnswers, startup, discoveryDraft);
      const draft = await buildInteractiveFoundation(startup.repoPath, scan, finalized, discoveryDraft ?? startup.discoveryDraft);
      setDiscoveryDraft(draft);
      setDiscoveryStep('draft_review');
      await persistDiscoveryDraft(startup.repoPath, draft, discoveryMode ?? 'interactive', scan);
      appendTranscript(setTranscript, {
        id: nextId(),
        kind: 'agent_summary',
        message: 'Interactive foundation draft is ready for review.',
      });
      appendTranscript(setTranscript, {
        id: nextId(),
        kind: 'system',
        message: 'Type `approve`, `edit`, `regenerate`, or `skip`.',
      });
    }
  }, [
    discoveryAnswers,
    discoveryDraft,
    discoveryMode,
    discoveryQuestionIndex,
    discoveryStep,
    promptDiscoveryQuestion,
    startup,
  ]);

  const submitComposer = useCallback(async (): Promise<void> => {
    const input = draft.trim();

    if (discoveryRequired) {
      if (input.length > 0) {
        appendTranscript(setTranscript, {
          id: nextId(),
          kind: 'user_input',
          message: input,
        });
      }
      await submitDiscovery(input);
      setDraft('');
      return;
    }

    if (boundaryResolverRef.current) {
      if (input.length > 0) {
        appendTranscript(setTranscript, {
          id: nextId(),
          kind: 'user_input',
          message: input,
        });
        resolveBoundary({ kind: 'redirect', request: input });
        appendTranscript(setTranscript, {
          id: nextId(),
          kind: 'system',
          message: 'Redirect sent.',
        });
      } else {
        resolveBoundary({ kind: 'pause' });
        appendTranscript(setTranscript, {
          id: nextId(),
          kind: 'paused',
          message: 'Paused at the current boundary.',
        });
      }
      setDraft('');
      return;
    }

    if (busy) {
      return;
    }

    if (!input) {
      if (resumeAvailable) {
        appendTranscript(setTranscript, {
          id: nextId(),
          kind: 'system',
          message: 'Resuming active run.',
        });
        await runOperator();
      }
      return;
    }

    appendTranscript(setTranscript, {
      id: nextId(),
      kind: 'user_input',
      message: input,
    });
    setDraft('');
    await runOperator(input);
  }, [busy, discoveryRequired, draft, resolveBoundary, resumeAvailable, runOperator, submitDiscovery]);

  useInput((input, key) => {
    if (key.escape) {
      onExitAction?.('exit');
      exit();
      return;
    }

    if (key.ctrl && input.toLowerCase() === 'v') {
      setShowDetails((current) => !current);
      return;
    }

    if (boundaryResolverRef.current && key.ctrl && input.toLowerCase() === 'y') {
      resolveBoundary({ kind: 'proceed' });
      appendTranscript(setTranscript, {
        id: nextId(),
        kind: 'system',
        message: 'Approval granted.',
      });
      return;
    }

    if (boundaryResolverRef.current && key.ctrl && input.toLowerCase() === 'p') {
      resolveBoundary({ kind: 'pause' });
      appendTranscript(setTranscript, {
        id: nextId(),
        kind: 'paused',
        message: 'Paused at the current boundary.',
      });
      return;
    }

    if (!boundaryResolverRef.current && key.ctrl) {
      const normalized = input.toLowerCase();
      if (normalized === 'g') {
        appendTranscript(setTranscript, {
          id: nextId(),
          kind: 'system',
          message: 'Opening provider setup studio...',
        });
        onExitAction?.('configure_providers');
        exit();
        return;
      }
      if (normalized === 'r') {
        void runSteeringAction('resume');
        return;
      }
      if (normalized === 't') {
        void runSteeringAction('retry');
        return;
      }
      if (normalized === 'n') {
        void runSteeringAction('replan');
        return;
      }
      if (normalized === 'o') {
        void runSteeringAction('show_plan');
        return;
      }
      if (normalized === 'f') {
        void runSteeringAction('inspect_failure');
        return;
      }
      if (normalized === 'l') {
        void runSteeringAction('inspect_logs');
        return;
      }
      if (normalized === 'u') {
        void runSteeringAction('revise_foundation');
        return;
      }
      if (normalized === 'd') {
        void runSteeringAction('dismiss_completed');
        return;
      }
      if (normalized === 'k') {
        void runSteeringAction('repair_state');
        return;
      }
    }

    if (key.return) {
      void submitComposer();
      return;
    }

    if (key.backspace || key.delete) {
      setDraft((current) => current.slice(0, -1));
      return;
    }

    if (key.ctrl || key.meta || key.tab || key.upArrow || key.downArrow || key.leftArrow || key.rightArrow) {
      return;
    }

    if (input.length > 0) {
      setDraft((current) => current + input);
    }
  });

  const transcriptRows = useMemo(() => {
    const reserved = pendingBoundary ? 16 : 11;
    return Math.max(6, rows - reserved);
  }, [pendingBoundary, rows]);

  const orchestratorState: 'idle' | 'running' | 'awaiting-approval' | 'paused' = boundaryResolverRef.current
    ? 'awaiting-approval'
    : busy
      ? 'running'
      : resumeAvailable
        ? 'paused'
        : 'idle';

  const startupHint = discoveryRequired
    ? 'Discovery is required before normal execution.'
    : !startup.profileValid
      ? 'No valid active provider profile. Press Ctrl+G to configure providers.'
    : recoveryState === 'inconsistent'
      ? 'State mismatch detected. Use Ctrl+K to run deterministic repair.'
      : recoveryState === 'blocked'
        ? 'Blocked task detected. Use Ctrl+T retry, Ctrl+N replan, or Ctrl+L logs.'
        : recoveryState === 'failed'
          ? 'Failed attempt detected. Use Ctrl+F failure details or Ctrl+T retry.'
    : busy
      ? 'Working...'
      : boundaryResolverRef.current
        ? 'Resolve the approval boundary from the composer.'
        : resumeAvailable
          ? 'Press Enter to resume the active run, or type a redirect.'
          : 'Type your request and press Enter.';

  const composerPlaceholder = discoveryRequired
    ? 'Continue discovery from the prompt shown above...'
    : !startup.profileValid
      ? 'Ctrl+G to open provider setup studio...'
    : recoveryState === 'inconsistent'
      ? 'Ctrl+K repair state, or type a recovery redirect...'
    : boundaryResolverRef.current
      ? 'Type redirect and press Enter, or press Enter to pause.'
      : resumeAvailable
        ? 'Press Enter to resume, or type a new request.'
        : 'Describe what you want to get done...';

  return (
    <Box flexDirection="column" height={rows}>
      <HeroCard mode={modeRef.current} startupHint={startupHint} />
      <EnvironmentStrip
        repoName={startup.repoName}
        branch={startup.branch}
        profileName={startup.profileName}
        provider={startup.provider}
        modelStrategy={startup.modelStrategy}
        model={startup.model}
        modelAvailability={startup.modelAvailability}
        capabilitySource={startup.capabilitySource}
        validationFreshness={startup.validationFreshness}
        authStatus={startup.authStatus}
        authSource={startup.authSource}
        runtimeReady={startup.hasScrimbleDir}
        orchestratorState={orchestratorState}
        activeRequest={activeRequest}
      />
      {discoveryRequired ? (
        <Box borderStyle="round" borderColor="magenta" paddingX={1} flexDirection="column">
          <Text bold color="magenta">Project Discovery</Text>
          {startup.discoveryScan ? (
            <Text color="gray">
              Scan: {startup.discoveryScan.projectType} • languages={startup.discoveryScan.languages.join(', ') || 'unknown'} • frameworks={startup.discoveryScan.frameworks.join(', ') || 'none'} • packageManager={startup.discoveryScan.packageManager ?? 'unknown'}
            </Text>
          ) : null}
          <Text color="gray">
            Mode: {discoveryMode ?? 'not selected'} • Step: {discoveryStep}
          </Text>
          {discoveryDraft && discoveryStep === 'draft_review' ? (
            <Box flexDirection="column">
              <Text>Draft: {discoveryDraft.projectName}</Text>
              <Text color="gray">Goal: {discoveryDraft.goal}</Text>
              <Text color="gray">Users: {discoveryDraft.targetUsers}</Text>
              <Text color="gray">Quality: {discoveryDraft.qualityPreference} • Timeline: {discoveryDraft.timeline}</Text>
            </Box>
          ) : null}
        </Box>
      ) : (latestActivity || startup.activeExecutionTaskId || startup.lastCompletedStep || recentOutcomes.length > 0) ? (
        <Box borderStyle="round" borderColor="gray" paddingX={1} flexDirection="column">
          <Text bold color="gray">Operator status</Text>
          <Text color="gray">State: {recoveryState}</Text>
          {startup.profileName ? (
            <Text color="gray">
              Profile: {startup.profileName} ({startup.provider ?? '-'}/{startup.modelStrategy === 'auto' ? 'auto' : startup.model ?? '-'})
            </Text>
          ) : null}
          {startup.authStatus ? (
            <Text color={startup.authStatus === 'ready' ? 'green' : startup.authStatus === 'missing' ? 'yellow' : 'red'}>
              Auth: {startup.authStatus}{startup.authSource ? ` (${startup.authSource})` : ''}
            </Text>
          ) : null}
          {startup.capabilitySource ? (
            <Text color={startup.capabilitySource === 'live' ? 'green' : startup.capabilitySource === 'cached' ? 'yellow' : 'gray'}>
              Capabilities: {startup.capabilitySource}
              {startup.validationFreshness ? ` (${startup.validationFreshness})` : ''}
              {startup.validatedAt ? ` @ ${startup.validatedAt}` : ''}
              {startup.modelAvailability ? ` • model=${startup.modelAvailability}` : ''}
            </Text>
          ) : null}
          {startup.activeExecutionTaskId ? (
            <Text color="gray">
              Active task: {startup.activeExecutionTaskId} ({startup.activeExecutionPhase ?? 'executing'})
            </Text>
          ) : null}
          {startup.lastCompletedStep ? <Text color="gray">Last step: {startup.lastCompletedStep}</Text> : null}
          {latestActivity ? <Text color="gray">Latest: {latestActivity}</Text> : null}
          {nextAction ? <Text color="gray">Next: {nextAction}</Text> : null}
          {recoveryMessage ? <Text color="yellow">Recovery: {recoveryMessage}</Text> : null}
          {availableRecoveryActions.length > 0 ? (
            <Box flexDirection="column">
              <Text color="gray">Actions:</Text>
              {availableRecoveryActions.slice(0, 4).map((action) => (
                <Text key={action.kind} color="gray">
                  {action.label} — {action.description}
                </Text>
              ))}
            </Box>
          ) : null}
          {recentOutcomes.length > 0 ? (
            <Box flexDirection="column">
              <Text color="gray">Recent runs:</Text>
              {recentOutcomes.slice(0, 3).map((outcome) => (
                <Text key={`${outcome.completedAt}-${outcome.request}`} color="gray">
                  {outcome.status} • {outcome.request} • {outcome.summary}
                </Text>
              ))}
            </Box>
          ) : null}
        </Box>
      ) : null}
      <TranscriptPane entries={transcript} showDetails={showDetails} maxEntries={transcriptRows} />
      {pendingBoundary ? <ApprovalCard boundary={pendingBoundary} actionable={Boolean(boundaryResolverRef.current)} /> : null}
      <Composer draft={draft} disabled={busy && !boundaryResolverRef.current} placeholder={composerPlaceholder} />
      <FooterHints awaitingApproval={Boolean(boundaryResolverRef.current)} />
    </Box>
  );
}
